export enum LocalStorageKey {
  TIME_DISPLAY = 'TIME_DISPLAY',
  LANGUAGE = 'LANGUAGE',
  ANIMATED_BG = 'ANIMATED_BG',

  FARES_TYPE = 'FARES_TYPE',
  FARES_PASSENGER_TYPE = 'FARES_PASSENGER_TYPE',
}
