export enum Stop {
  TUM = 'TUM', // Tuen Mun
  SIH = 'SIH', // Siu Hong
  TIS = 'TIS', // Tin Shui Wai
  LOP = 'LOP', // Long Ping
  YUL = 'YUL', // Yuen Long
  KSR = 'KSR', // Kam Sheung Road
  TWW = 'TWW', // Tsuen Wan West
  MEF = 'MEF', // Mei Foo
  NAC = 'NAC', // Nam Cheong
  AUS = 'AUS', // Austin
  ETS = 'ETS', // East Tsim Sha Tsui
  HUH = 'HUH', // Hung Hom
  HOM = 'HOM', // Ho Man Tin
  TKW = 'TKW', // To Kwa Wan
  SUW = 'SUW', // Sung Wong Toi
  KAT = 'KAT', // Kai Tak
  DIH = 'DIH', // Diamond Hill
  HIK = 'HIK', // Hin Keng
  TAW = 'TAW', // Tai Wai
  CKT = 'CKT', // Che Kung Temple
  STW = 'STW', // Sha Tin Wai
  CIO = 'CIO', // City One
  SHM = 'SHM', // Shek Mun
  TSH = 'TSH', // Tai Shui Hang
  HEO = 'HEO', // Heng On
  MOS = 'MOS', // Ma On Shan
  WKS = 'WKS', // Wu Kai Sha
  ADM = 'ADM', //  Admiralty
  EXC = 'EXC', //  Exhibition Centre
  MKK = 'MKK', //  Mong Kok East
  KOT = 'KOT', //  Kowloon Tong
  SHT = 'SHT', //  Sha Tin
  FOT = 'FOT', //  Fo Tan
  RAC = 'RAC', //  Racecourse
  UNI = 'UNI', //  University
  TAP = 'TAP', //  Tai Po Market
  TWO = 'TWO', //  Tai Wo
  FAN = 'FAN', //  Fanling
  SHS = 'SHS', //  Sheung Shui
  LOW = 'LOW', //  Lo Wu
  LMC = 'LMC', //  Lok Ma Chau
  TSW = 'TSW', // Tsuen Wan
  TWH = 'TWH', // Tai Wo Hau
  KWH = 'KWH', // Kwai Hing
  KWF = 'KWF', // Kwai Fong
  LAK = 'LAK', // Lai King
  LCK = 'LCK', // Lai Chi Kok
  CSW = 'CSW', // Cheung Sha Wan
  SSP = 'SSP', // Sham Shui Po
  PRE = 'PRE', // Prince Edward
  MOK = 'MOK', // Mong Kok
  YMT = 'YMT', // Yau Ma Tei
  JOR = 'JOR', // Jordan
  TST = 'TST', // Tsim Sha Tsui
  CEN = 'CEN', // Central
  HOK = 'HOK', // Hong Kong
  KOW = 'KOW', // Kowloon
  OLY = 'OLY', // Olympic
  TSY = 'TSY', // Tsing Yi
  SUN = 'SUN', // Sunny Bay
  TUC = 'TUC', // Tung Chung
}
